### ISSUE TITLE
Sample data installation no longer works

### ISSUE THREAD

**Issue by Vinai** [rgranadino/mage2_vagrant#25]
The method of installing the sample data has changed. It no longer works as with Magento 1.
It first has to be added as a composer dependency, and after the package is installed an install script needs to be executed

```sh
composer config repositories.magento composer http://packages.magento.com
composer require magento/sample-data:0.42.0-beta6 magento/sample-data-media:0.42.0-beta1 --dev
php -f dev/tools/Magento/Tools/SampleData/install.php -- --admin_username=admin
```
More information:
http://devdocs.magento.com/guides/v1.0/install-gde/install/sample-data.html

**Comment by rgranadino** [comment]
Thanks for bringing this up, I'll try and take a look over the next week or so and try to get it updated.

**Comment by refaelgold** [comment]
please update when the issue is close . 

Thanks

**Comment by refaelgold** [comment]
Hi still have this issue and i really try all solution and nothing works!

```
Installing theme:
.
exception 'ReflectionException' with message 'Class Magento\Framework\Store\StoreManagerInterface does not exist' in /vagrant/data/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:29
Stack trace:
#0 /vagrant/data/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(29): ReflectionParameter->getClass()
#1 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Tools\\S...')
#2 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(73): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Tools\\S...')
#3 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...')
#4 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tools\\S...')
#5 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Tools\\S...', NULL, 'storeManager', 'Magento\\Tools\\S...')
#6 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Tools\\S...', Array, Array)
#7 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...')
#8 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tools\\S...')
#9 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Tools\\S...', NULL, 'customerSetup', 'Magento\\Tools\\S...')
#10 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Tools\\S...', Array, Array)
#11 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...', Array)
#12 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/SetupFactory.php(38): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Tools\\S...')
#13 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/Installer.php(82): Magento\Tools\SampleData\SetupFactory->create('Magento\\Tools\\S...')
#14 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/InstallerApp.php(96): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User))
#15 /vagrant/data/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Tools\SampleData\InstallerApp->launch()
#16 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/install.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Tools\SampleData\InstallerApp))
#17 {main}

Next exception 'ReflectionException' with message 'Class Magento\Framework\Store\StoreManagerInterface does not exist' in /vagrant/data/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:37
Stack trace:
#0 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Tools\\S...')
#1 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(73): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Tools\\S...')
#2 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...')
#3 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tools\\S...')
#4 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Tools\\S...', NULL, 'storeManager', 'Magento\\Tools\\S...')
#5 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Tools\\S...', Array, Array)
#6 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...')
#7 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tools\\S...')
#8 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Tools\\S...', NULL, 'customerSetup', 'Magento\\Tools\\S...')
#9 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Tools\\S...', Array, Array)
#10 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...', Array)
#11 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/SetupFactory.php(38): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Tools\\S...')
#12 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/Installer.php(82): Magento\Tools\SampleData\SetupFactory->create('Magento\\Tools\\S...')
#13 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/InstallerApp.php(96): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User))
#14 /vagrant/data/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Tools\SampleData\InstallerApp->launch()
#15 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/install.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Tools\SampleData\InstallerApp))
```

**Comment by therouv** [comment]
There is an issue in the Magento2 repository for this topic: https://github.com/magento/magento2/issues/1216
We will check and try again after the issue is resolved there.
